apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helse-spion
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /health/isalive
    initialDelay: 10
    timeout: 1
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /health/isready
    initialDelay: 10
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  ingresses:
    - https://helse-spion.dev.nav.no
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 64Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/helse-spion/default
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvhelsespion
      - mountPath: /var/run/secrets/nais.io/apigw/altinn
        kvPath: /apikey/apigw/dev/eksternapp.altinn.serviceowner/helse-spion_q1
  webproxy: true
  secureLogs:
    enabled: true
  envFrom:
    - configmap: loginservice-idporten # tilgjengeliggjør LOGINSERVICE_IDPORTEN_DISCOVERY_URL og LOGINSERVICE_IDPORTEN_AUDIENCE
    # servicebrukerens passord som er  hentet fra vault og lagt inn slik: https://doc.nais.io/security/secrets/kubernetes-secrets/
    - secret: service-user-password
    - secret: altinn-user-password
    - secret: altinn-api-gw-keys
  env:
  - name: KOIN_PROFILE
    value: PREPROD
  - name: DATABASE_HOST
    value: b27dbvl008.preprod.local
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: helse-spion
  - name: VAULT_MOUNTPATH
    value: postgresql/preprod-fss/
  - name: ALTINN_SERVICE_OWNER_GW_URL
    value: https://api-gw-q1.adeo.no/ekstern/altinn/api/serviceowner
  - name: VEDTAK_TOPICNAME
    value: aapen-helse-sporbar
  - name: KAFKA_ENDPOINTS
    value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
  - name: SECURITYTOKENSERVICE_REST_URL
    value: https://security-token-service.nais.preprod.local/rest/v1/sts/token

  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: helse-spion-db
            diskAutoresize: true