apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helse-spion
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 10
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  ingresses:
    - https://helse-spion.nais.preprod.local
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 64Mi
  vault:
    enabled: true
    paths:
      - kvPath: kv/preprod/fss/helse-spion/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: apikey/apigw/dev/eksternapp.altinn.serviceowner/helse-spion_q1
        mountPath: /apigw/altinn/x-nav-apiKey
  webproxy: true
  env:
  - name: ENVIRONMENT
    value: "development"
  - name: DATABASE_HOST
    value: b27dbvl008.preprod.local
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: helse-spion
  - name: VAULT_MOUNTPATH
    value: postgresql/preprod-fss/
