apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: helse-spion
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 10
    periodSeconds: 3
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 10
    timeout: 1
    periodSeconds: 3
    failureThreshold: 10
  ingresses:
    - https://helse-spion.nais.adeo.no
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 64Mi
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/helse-spion/default
        mountPath: /var/run/secrets/nais.io/vault
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvhelsespion
      - mountPath: /var/run/secrets/nais.io/apigw/altinn
        kvPath: /apikey/apigw/prod/eksternapp.altinn.serviceowner/helse-spion
  webproxy: true
  secureLogs:
    enabled: true
  envFrom:
    - configmap: loginservice-idporten # tilgjengeliggjør LOGINSERVICE_IDPORTEN_DISCOVERY_URL og LOGINSERVICE_IDPORTEN_AUDIENCE

  env:
  - name: KOIN_PROFILE
    value: PROD
  - name: DATABASE_HOST
    value: a01dbvl010.adeo.no
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: helse-spion
  - name: VAULT_MOUNTPATH
    value: postgresql/prod-fss/
  - name: KAFKA_ENDPOINTS
    value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443
  - name: VEDTAK_TOPICNAME
    value: aapen-helse-sporbar
  - name: PDL_URL
    value: https://pdl-api.nais.adeo.no/graphql
  - name: SECURITYTOKENSERVICE_REST_URL
    value: https://security-token-service.nais.adeo.no/rest/v1/sts/token

